INSERT INTO presentador (nombre_presentador) VALUES ('Sylvia Ríos');
INSERT INTO presentador (nombre_presentador) VALUES ('Sandra Sánchez');
INSERT INTO presentador (nombre_presentador) VALUES ('Miryam Almanza');
INSERT INTO presentador (nombre_presentador) VALUES ('Maricarmen Figueroa');
INSERT INTO presentador (nombre_presentador) VALUES ('Julieta Orduña');
INSERT INTO presentador (nombre_presentador) VALUES ('Clara Martínez');
INSERT INTO presentador (nombre_presentador) VALUES ('Mónica García');
INSERT INTO presentador (nombre_presentador) VALUES ('Administrador del sitio');
INSERT INTO presentador (nombre_presentador) VALUES ('Edilberto Aldán');
INSERT INTO presentador (nombre_presentador) VALUES ('Humberto Capetillo');
INSERT INTO presentador (nombre_presentador) VALUES ('Gustavo Sifuentes Valadez');
INSERT INTO presentador (nombre_presentador) VALUES ('Sara Padilla');
INSERT INTO presentador (nombre_presentador) VALUES ('Rogelio Pérez');
INSERT INTO presentador (nombre_presentador) VALUES ('Juan Manuel Rodríguez');
INSERT INTO presentador (nombre_presentador) VALUES ('Liam Adrián');
INSERT INTO presentador (nombre_presentador) VALUES ('Ricardo Vega');
INSERT INTO presentador (nombre_presentador) VALUES ('Luis Carrasco');
INSERT INTO presentador (nombre_presentador) VALUES ('Felipe Márquez');
INSERT INTO presentador (nombre_presentador) VALUES ('Samuel Ornelas');
INSERT INTO presentador (nombre_presentador) VALUES ('M.E. Adriana Acosta Dávila');
INSERT INTO presentador (nombre_presentador) VALUES ('Ale de los Ríos');
INSERT INTO presentador (nombre_presentador) VALUES ('Vladimir Guerrero');
INSERT INTO presentador (nombre_presentador) VALUES ('Julio Cortez');
INSERT INTO presentador (nombre_presentador) VALUES ('Isaac Benitez "El Cheche"');
INSERT INTO presentador (nombre_presentador) VALUES ('Gerardo "Roger" Loera');
INSERT INTO presentador (nombre_presentador) VALUES ('Luis Arturo Rosas Malacara');
INSERT INTO presentador (nombre_presentador) VALUES ('Dra. Consuelo Meza Márquez');
INSERT INTO presentador (nombre_presentador) VALUES ('Juan José Láriz Durón');
INSERT INTO presentador (nombre_presentador) VALUES ('Fernando López');
INSERT INTO presentador (nombre_presentador) VALUES ('Leticia Torres Soto');
INSERT INTO presentador (nombre_presentador) VALUES ('Gustavo Meza Medina');
INSERT INTO presentador (nombre_presentador) VALUES ('Daniela Malike Ledesma Muñoz');
INSERT INTO presentador (nombre_presentador) VALUES ('Alejandro Márquez Díaz del Castillo');
INSERT INTO presentador (nombre_presentador) VALUES ('Juan Reyes Unzueta');
INSERT INTO presentador (nombre_presentador) VALUES ('Sara Mireya Carmona');
INSERT INTO presentador (nombre_presentador) VALUES ('Sergio Castañeda Pacheco');
INSERT INTO presentador (nombre_presentador) VALUES ('Mireya Castañeda');
INSERT INTO presentador (nombre_presentador) VALUES ('Leticia Martell');
INSERT INTO presentador (nombre_presentador) VALUES ('Mtro. David Roberto Barba');
INSERT INTO presentador (nombre_presentador) VALUES ('Manuel Palestina');
INSERT INTO presentador (nombre_presentador) VALUES ('Liliana Vargas Ortega');
INSERT INTO presentador (nombre_presentador) VALUES ('Gerardo Rangel Escobedo');
INSERT INTO presentador (nombre_presentador) VALUES ('Ernesto Martínez Frausto');
INSERT INTO presentador (nombre_presentador) VALUES ('Ramón Arredondo');
INSERT INTO presentador (nombre_presentador) VALUES ('Leticia Medina Andrade');
INSERT INTO presentador (nombre_presentador) VALUES ('Oswaldo Rodriguez');
INSERT INTO presentador (nombre_presentador) VALUES ('Mario Gerardo de Ávila');
INSERT INTO presentador (nombre_presentador) VALUES ('Enrique Rodríguez Varela');
INSERT INTO presentador (nombre_presentador) VALUES ('Carlos Reyes Sahagún');
INSERT INTO presentador (nombre_presentador) VALUES ('Andrés Reyes');
INSERT INTO presentador (nombre_presentador) VALUES ('Gabriela Hermosillo');
INSERT INTO presentador (nombre_presentador) VALUES ('Irlanda Godina');
INSERT INTO presentador (nombre_presentador) VALUES ('Walkyria Torres');
INSERT INTO presentador (nombre_presentador) VALUES ('Pavel Zavala');
INSERT INTO presentador (nombre_presentador) VALUES ('Rafael Antonio Polo López');
INSERT INTO presentador (nombre_presentador) VALUES ('Cami');
INSERT INTO presentador (nombre_presentador) VALUES ('Nohemí Gubisha Ruiz Moran');
INSERT INTO presentador (nombre_presentador) VALUES ('');
INSERT INTO presentador (nombre_presentador) VALUES ('Mtro. Juan Pablo Correa');
INSERT INTO presentador (nombre_presentador) VALUES ('Mtra. Karla Ledezma');
INSERT INTO presentador (nombre_presentador) VALUES ('Dra. Irma Susana Carbajal Vaca');
INSERT INTO presentador (nombre_presentador) VALUES ('Dr. Raúl W. Capistrán Gracia');
INSERT INTO genero (nombre_genero) VALUES ('De revista');
INSERT INTO genero (nombre_genero) VALUES ('Hablado');
INSERT INTO genero (nombre_genero) VALUES ('Teatro');
INSERT INTO genero (nombre_genero) VALUES ('Informativo');
INSERT INTO genero (nombre_genero) VALUES ('Musical');
INSERT INTO genero (nombre_genero) VALUES ('Educativo');
INSERT INTO genero (nombre_genero) VALUES ('Opinión');
INSERT INTO genero (nombre_genero) VALUES ('Variado');
INSERT INTO genero (nombre_genero) VALUES ('Entrevistas');
INSERT INTO genero (nombre_genero) VALUES ('Formación Docente');
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('50 años de la UAA al ritmo de la música', 'None', 'Un espacio para recordar la hitoria de la Universidad Autónoma de Aguascalientes acompañando con la musica que se escuchaba en esos años.');
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('A Escena', 'https://radio.uaa.mx/wp-content/uploads/2021/08/a-escena-300x300.png', 'Programa de revista cultural que promociona y difunde las diversas actividades artisticas del Estado de Aguascalientes. Su contenido se basa en entrevistas, cápsulas de notas de la semana, efemérides teatrales; asimismo cartelera y secciones de ópera, zarzuela, cine y temas del teatro.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (2, 'Martes', '20:30', '21:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (2, 'Miércoles', '02:00', '03:00', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (2, 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (2, 2);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (2, 3);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (2, 4);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (2, 5);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (2, 6);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (2, 1);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (2, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (2, 3);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('A la vuelta del vinilo', 'None', 'DJ Chuy Montañez nos trae lo mejor de la música electrónica, para comenzar… o terminar la fiesta.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (3, 'Sábado', '00:00', '02:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (3, 'Domingo', '03:00', '05:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('ADN de la Salud', 'https://radio.uaa.mx/wp-content/uploads/2021/08/5-300x300.png', 'Espacio informativo a través del cual se promociona el bienestar integral de las personas a través de información preventiva en temas de salud, con el acompañamiento de expertos en el tema que forman parte de la UAA. Además de dar a conocer los servicios que ofrece la Unidad Médico Didáctica.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (4, 'Jueves', '10:30', '11:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (4, 7);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (4, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('After', 'https://radio.uaa.mx/wp-content/uploads/2021/08/3a-After-01-300x300.png', 'Es una espacio dedicado a musica electronica.');
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (5, 8);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (5, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Algo Que Decir…', 'https://radio.uaa.mx/wp-content/uploads/2021/11/algoquedecir-300x300.png', 'Programa editorial sobre temas de actualidad en México y Aguasclientes');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (6, 'Lunes', '19:00', '19:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (6, 9);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Altavoz', 'None', 'Producción en el que semana a semana se da a conocer lo más importante ocurrido en materia de investigación y posgrados en la Universidad Autónoma de Aguascalientes.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (7, 'Lunes', '10:30', '11:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (7, 10);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (7, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Archivos, historias y otros relatos', 'https://radio.uaa.mx/wp-content/uploads/2023/08/Captura-de-Pantalla-2024-04-10-a-las-13.39.28-300x269.png', 'Un espacio de conocimiento e historia referente a los acontencimientos de la Universidad Autónoma de Aguascalientes');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (8, 'Martes', '11:00', '11:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Arena Mestiza', 'https://radio.uaa.mx/wp-content/uploads/2024/04/Captura-de-Pantalla-2024-04-10-a-las-13.19.11.png', 'Programa sobre los acontecimientos más destacados tanto de la charrería como de la tauromaquia, sucedidos en Aguascalientes y el resto del país y en el caso de esta última España, Portugal, Francia, México, Colombia, Ecuador, Venezuela y Perú, resaltando sobre todo aquellos en donde estén involucrados personajes taurinos de la entidad.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (9, 'Domingo', '10:00', '11:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Artefacto', 'https://radio.uaa.mx/wp-content/uploads/2021/08/artefacto-300x300.jpg', 'Artefacto. Programa radiofónico del Instituto Cultural de Aguascalientes, co-producido por los departamentos de Comunicación y Tecnología e Innovación. Artefacto es un programa cultural e informativo en donde colaboran compañeros de diversas áreas del Instituto Cultural de Aguascalientes, además de invitados especiales. Se manejan temas sobre museos y galerías, investigación cultural, literatura, cine, casas de cultura en los municipios del Estado, cuenta cuentos y entrevistas; así mismo se manejan efemérides y cápsulas musicales. Artefacto es un programa cultural e informativo en donde colaboran compañeros de diversas áreas del Instituto Cultural de Aguascalientes, además de invitados especiales. Se manejan temas sobre museos y galerías, investigación cultural, literatura, cine, casas de cultura en los municipios del Estado, cuenta cuentos y entrevistas; así mismo se manejan efemérides y cápsulas musicales.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (10, 'Miércoles', '13:30', '14:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (10, 11);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (10, 6);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (10, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Ases Históricos', 'https://radio.uaa.mx/wp-content/uploads/2021/08/ases-300x300.png', 'Ases históricos es un programa de radio de los estudiantes de la licenciatura en historia, dedicado a la difusión de conocimiento histórico.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (11, 'Miércoles', '17:00', '17:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (11, 12);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (11, 13);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (11, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (11, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Aún Brilla', 'None', 'Programa musical de Oldies');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (12, 'Lunes', '21:30', '23:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (12, 'Martes', '02:00', '03:30', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (12, 14);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (12, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Bloque musical – Bossa & Chill', 'https://radio.uaa.mx/wp-content/uploads/2023/06/Captura-de-Pantalla-2024-04-10-a-las-14.25.16-300x226.png', 'Para comenzar tu día, la mejor selección de bossanova, chill & lounge');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (13, 'Lunes', '08:30', '09:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (13, 'Martes', '08:30', '09:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (13, 'Miércoles', '08:30', '09:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (13, 'Jueves', '08:30', '09:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (13, 'Viernes', '08:30', '09:00', 0);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (13, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Bloque Musical – Música del Mundo', 'https://radio.uaa.mx/wp-content/uploads/2024/04/la_musica_del_fin_del_mundo_3965-300x226.webp', 'La mejor selección de música del mundo para que comiences tu mañana');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (14, 'Lunes', '10:00', '10:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (14, 'Martes', '10:00', '10:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (14, 'Miércoles', '10:00', '10:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (14, 'Jueves', '10:00', '10:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Bloque Musical – Rock en Español', 'https://radio.uaa.mx/wp-content/uploads/2024/04/d82bf76c-52ea-4b5b-9c49-89cfd1d91b22-300x300.png', 'Lo mejor del rock iberoamericano, para recargar la pila por las tardes');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (15, 'Lunes', '15:30', '16:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (15, 'Martes', '15:30', '16:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (15, 'Miércoles', '15:30', '16:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (15, 'Jueves', '15:30', '16:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (15, 'Viernes', '15:30', '16:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Butaca Jazz', 'https://radio.uaa.mx/wp-content/uploads/2021/08/butaca-jazz-300x300.png', 'Un espacio musical donde se presenta Música del género Jazz.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (16, 'Lunes', '00:00', '01:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (16, 'Domingo', '16:00', '17:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (16, 15);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (16, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('#SoyComunicación Radio: Ce de Casa', 'https://radio.uaa.mx/wp-content/uploads/2024/04/Captura-de-Pantalla-2024-04-04-a-las-9.47.15-300x135.png', 'Programa del departamento académico de comunicación');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (17, 'Miércoles', '16:00', '17:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (17, 'Jueves', '04:00', '05:00', 1);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Cine Indiscreto', 'https://radio.uaa.mx/wp-content/uploads/2022/11/Cine-Indiscreto-1-300x300.png', 'Un programa dedicado al análisis del cine desde el punto de vista de la Sociología.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (18, 'Martes', '18:00', '19:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (18, 'Miércoles', '03:00', '04:00', 1);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (18, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (18, 7);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Cinergis', 'https://radio.uaa.mx/wp-content/uploads/2021/08/cinergis-300x300.png', 'Cinergis, programa de radio especializado en cine. Entrevistas, soundtracks, información del séptimo arte y todo lo relacionado al apasionante mundo del cine.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (19, 'Martes', '21:30', '22:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (19, 16);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (19, 17);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (19, 18);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (19, 1);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (19, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (19, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (19, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('City Pop', 'https://radio.uaa.mx/wp-content/uploads/2024/08/Captura-de-Pantalla-2024-08-08-a-las-15.20.45-300x209.png', 'Programa musical que nos presenta la historia y los mejores exponentes del Género musical City Pop (Sub-género del J-Pop).');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (20, 'Viernes', '02:00', '02:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (20, 19);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Comunitec', 'https://radio.uaa.mx/wp-content/uploads/2021/08/comunitec-1-300x300.png', 'Programa informativo acerca de las actividades que se realizan en el Instituto Tecnológico de Aguascalientes.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (21, 'Martes', '10:30', '11:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (21, 20);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (21, 9);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (21, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (21, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (21, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Contra Rutina', 'https://radio.uaa.mx/wp-content/uploads/2024/04/contra-rutina-300x290.png', '¡La gozadera de la Cultura!');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (22, 'Lunes', '11:00', '11:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Contractura mental', 'None', 'Este espacio radiofónico tendrá una riqueza expresiva a través de un grupo de amigos y compañeros que comparten todo, algo y nada; es seguro que con sus semejanzas se sientan acompañados en este planeta, y tal vez, en el trayecto de su vida; o quizá las diferencias consigan lograr una sinapsis donde sus mentes salten en pedazos.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (23, 'Jueves', '14:00', '14:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Coversando', 'https://radio.uaa.mx/wp-content/uploads/2023/06/coversando-300x300.jpg', 'Programa musical que pretende compartir diferentes versiones en distintos generos de las canciones que ya conoces.');
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (24, 21);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (24, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Cuadrante Sonoro', 'https://radio.uaa.mx/wp-content/uploads/2021/07/logo_green-300x300.png', 'Un acercamiento a las más diversas voces musicales de los pueblos del mundo.');
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('#Cultura Freak', 'https://radio.uaa.mx/wp-content/uploads/2021/08/Anchor-16a-temporada-300x300.jpg', '#CulturaFreak es un espacio de discusión, análisis y (des)información sobre todo lo relacionado del mundo de los Cómics, Manga, Anime, Películas de Culto, Series, Literatura Fantástica, Juegos de Rol, Juegos de Cartas Coleccionables, Wargames y demás cosas que antes eran de Frikis, pero ahora se han ganado un lugar dentro del gusto y la Cultura Popular en México y el Mundo. Todo esto y muchas incoherencias más, platicado y a veces analizado por tus 4 Frikis favoritos desde su muy particular y extraño punto de vista.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (26, 'Lunes', '20:30', '21:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (26, 'Martes', '00:00', '01:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (26, 'Sábado', '16:00', '17:00', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (26, 22);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (26, 23);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (26, 24);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (26, 25);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (26, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (26, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (26, 7);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Cultura Radiante', 'https://radio.uaa.mx/wp-content/uploads/2021/08/cultura-radiante-300x300.png', 'Programa de difusión cultural y actividades del IMAC =Intituto Municipal Aguascalentense para la Cultura.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (27, 'Jueves', '17:30', '18:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (27, 26);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (27, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (27, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('De Mujer, Símbolo y Pensamiento', 'None', 'De mujeres… símbolo y pensamiento es un programa de revista que incorpora la mirada de género. Tiene como objetivo el brindar nuevos elementos simbólicos para que las personas en general, y las mujeres en particular, reflexionen sobre sí, recuperando la legitimidad de su deseo respecto a un protagonismo directo y personal y a la construcción de ciudadanía.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (28, 'Martes', '13:30', '14:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (28, 27);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (28, 1);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (28, 9);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (28, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (28, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (28, 5);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (28, 7);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (28, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Dilemas Éticos', 'https://radio.uaa.mx/wp-content/uploads/2021/08/Dilemas-Eticos-1e-300x300.png', 'Programa donde se analiza, de manera crítica, algunos dilemas éticos y morales que los profesionistas enfrentan dentro de su labor cotidiana, ello aunado de una meditación de dichas actividades.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (29, 'Martes', '17:00', '17:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (29, 28);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (29, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (29, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (29, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Dimensión Ótica', 'https://radio.uaa.mx/wp-content/uploads/2021/08/Dimension-Otica-boceto2-300x300.png', 'Musical de rock progresivo');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (30, 'Miércoles', '20:30', '22:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (30, 'Sábado', '22:00', '00:00', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (30, 29);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (30, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Discordia', 'https://radio.uaa.mx/wp-content/uploads/2024/04/401056481_1095266518571230_7270654784913750093_n-300x300.jpeg', 'Conoce los perfiles de creadores y compositores fuera de lo convencional que muestran a través de la producción auditiva su interpretación de la realidad y su influencia en los videojuegos, animaciones, cine, radio, publicidad, entorno social y cultural de las personas.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (31, 'Miércoles', '00:00', '01:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (31, 'Domingo', '18:00', '19:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Divertimento', 'None', 'Un espacio musical de musica clásica.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (32, 'Sábado', '05:30', '06:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (32, 'Domingo', '05:30', '06:00', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (32, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Educar para Transformar', 'https://radio.uaa.mx/wp-content/uploads/2021/08/upn-300x300.jpg', 'Programa radiofónico de la Universidad Pedagógica Nacional para la divulgación de temas educativos y afines al diario acontecer de las y los docentes de nuestro país.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (33, 'Viernes', '10:30', '11:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (33, 30);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (33, 31);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (33, 32);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (33, 33);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (33, 9);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (33, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (33, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('El acervo', 'None', 'Programa musical que comparte el material sonoro a resguardo de la fonoteca del edificio 14 en la unidad de radio Jose Davila Rodriguez');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (34, 'Lunes', '23:00', '23:30', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (34, 'Sábado', '14:30', '15:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (34, 21);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('El Arte del Buen Tunar', 'https://radio.uaa.mx/wp-content/uploads/2021/11/El-Arte-del-Buen-Tunar-300x300.png', 'Es un programa que trata de las estudiantinas de Aguascalientes, su historia y su recorrido, tambien tratando sobre el seminario de cultura mexicana y sus integrantes.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (35, 'Lunes', '18:00', '19:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('El aula', 'https://radio.uaa.mx/wp-content/uploads/2023/08/Captura-de-Pantalla-2024-04-10-a-las-13.35.27.png', 'Bienvenidos a El Aula');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (36, 'Jueves', '11:00', '11:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('El Canto de la Guitarra', 'None', 'Inicio. Bienvenida.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (37, 'Domingo', '06:00', '07:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (37, 34);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (37, 9);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (37, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (37, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (37, 5);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (37, 7);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('El Gallo', 'None', 'Programa de revista, dedicado a la difusión de música, información científica, tecnológica, de la institución y de entretenimiento, así como cápsulas y entrevistas de interés general.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (38, 'Lunes', '07:00', '08:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (38, 'Martes', '07:00', '08:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (38, 'Miércoles', '07:00', '08:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (38, 'Jueves', '07:00', '08:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (38, 'Viernes', '07:00', '08:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (38, 21);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (38, 1);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (38, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (38, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('El Gis', 'https://radio.uaa.mx/wp-content/uploads/2021/08/el-gis.png', 'Programa radiofónico El Gis, del Departamento de Formación y Actualización Académica.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (39, 'Miércoles', '10:30', '11:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (39, 35);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (39, 6);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (39, 9);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (39, 10);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (39, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('El Medio Tiempo', 'None', 'Entérate de lo más relevante en el mundo del deporte local, nacional e internacional');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (40, 'Lunes', '13:00', '13:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Emprendetodo', 'None', 'Emprendetodo es un programa enfocado a apoyar a la comunidad emprendedora, donde se habla de temas como marketing, administración, actualidad, entrevistamos emprendedores locales y foráneos con el fin de apoyarlos y proveer de consejos las y los nuevos emprendedores.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (41, 'Viernes', '11:30', '12:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Entera-t', 'https://radio.uaa.mx/wp-content/uploads/2021/08/entera-t-300x300.png', 'Programa de entrevistas a nuevas propuestas musicales');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (42, 'Martes', '01:00', '02:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (42, 'Sábado', '17:00', '18:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (42, 36);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (42, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Estación Política', 'https://radio.uaa.mx/wp-content/uploads/2021/11/estacionpolitica-300x300.jpg', 'Programa de análisis de temas políticos de actualidad por los alumnos de la carrera de ciencias políticas');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (43, 'Martes', '17:30', '18:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (43, 8);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (43, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (43, 7);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Rock Machine', 'https://radio.uaa.mx/wp-content/uploads/2023/06/PHOTO-2023-09-18-16-06-00-300x300.jpg', 'Programa musical de Rock en español');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (44, 'Lunes', '19:30', '20:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (44, 'Martes', '19:30', '20:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (44, 'Miércoles', '19:30', '20:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (44, 'Jueves', '19:30', '20:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (44, 'Viernes', '19:30', '20:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Finanzas y Negocios', 'None', 'Un programa dedicado al analisis de los temas financieros, políticos y económicos de la actualidad');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (45, 'Lunes', '17:00', '17:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (45, 37);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (45, 38);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (45, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Flamenco Radio', 'None', 'Programa musical de flamenco.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (46, 'Domingo', '07:00', '08:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (46, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Fonoteca 1370', 'https://radio.uaa.mx/wp-content/uploads/2023/06/Fonoteca-1370-logo-300x300.png', 'Un programa que rescata la historia de radio universidad a travez de los programas que se trasmitian desde sus inicios en la emisora.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (47, 'Miércoles', '18:30', '19:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (47, 'Jueves', '03:00', '04:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (47, 'Domingo', '15:00', '16:00', 1);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (47, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Generación Y', 'None', '¡La Frecuencia milenial!');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (48, 'Viernes', '18:00', '18:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (48, 'Sábado', '03:00', '03:30', 1);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Hablemos de Derechos Humanos', 'https://radio.uaa.mx/wp-content/uploads/2021/08/Acrobat-Document-300x300.png', 'Hablemos de derechos humanos es un programa en el que se informa y reflexiona sobre los derechos humanos, a través de entrevistas, noticias y artículos que nos permitan profundizar en nuestra realidad con la perspectiva de estos derechos.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (49, 'Sábado', '10:30', '11:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (49, 39);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (49, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (49, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Hablemos de Trabajo Social', 'None', 'None');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (50, 'Viernes', '11:00', '11:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Hasta que el Cuerpo Aguante', 'https://radio.uaa.mx/wp-content/uploads/2021/08/Hasta-que-el-Cuerpo-Aguante-1-300x300.png', 'Hasta que el cuerpo aguante, el recuerdo siempre presente, es un programa de radio con música de antaño que incluye boleros, rancheras, orquestas, trova yucateca y otros ritmos. Se dan a conocer grabaciones muy antiguas extraídas de antiguos discos de 78 rpm.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (51, 'Lunes', '05:00', '06:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (51, 'Martes', '05:00', '06:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (51, 'Miércoles', '05:00', '06:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (51, 'Jueves', '05:00', '06:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (51, 'Viernes', '05:00', '06:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (51, 'Domingo', '00:00', '03:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (51, 40);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (51, 41);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (51, 42);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (51, 43);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Hecho en Casa', 'https://radio.uaa.mx/wp-content/uploads/2021/08/hecho-en-casa-300x300.png', 'Programa de entrevistas a grupos de rock iberoamericanas.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (52, 'Jueves', '20:30', '21:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (52, 'Viernes', '02:30', '03:30', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (52, 44);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (52, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Hoy Filosofía', 'https://radio.uaa.mx/wp-content/uploads/2021/08/hoyfilosofia-300x300.jpg', 'Programa del departamento de filosofía en el que los profesores comparten sus conocimientos sobre temas específicos del ámbito filosófico y sus experiencias docentes. El conductor es el profesor responsable del programa correspondiente con base en la calendarización que se elabora semestralmente.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (53, 'Lunes', '13:30', '14:00', 0);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (53, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (53, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Hoy Toca Libro', 'https://radio.uaa.mx/wp-content/uploads/2021/11/hoytocalibro-300x300.png', 'Alumnos de la licenciatura de Letras Hispanicas nos comparten recomendaciones literarias.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (54, 'Jueves', '17:00', '17:30', 0);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (54, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (54, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (54, 7);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Independiente', 'https://radio.uaa.mx/wp-content/uploads/2021/11/Logo-independiente-300x300.png', 'Un espacio dedicado para la musica Independiente.');
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (55, 45);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Indiespensables', 'https://radio.uaa.mx/wp-content/uploads/2023/06/indiespensables-800x800px-300x300.png', 'Es un programa musical indie y sus diferentes variantes, con información de algún dato interesante que se realice en la universidad o a nivel estatal, nacional o internacional.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (56, 'Lunes', '14:30', '15:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (56, 'Martes', '14:30', '15:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (56, 'Miércoles', '14:30', '15:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (56, 'Jueves', '14:30', '15:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (56, 'Viernes', '14:30', '15:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (56, 19);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Interiores', 'https://radio.uaa.mx/wp-content/uploads/2022/04/logo-sm-b.png', 'Difusíon de las casas de las culturas de los municipos de Aguascalientes');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (57, 'Miércoles', '17:30', '18:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (57, 8);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (57, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Jazz Boulevard', 'https://radio.uaa.mx/wp-content/uploads/2024/04/Captura-de-Pantalla-2024-04-10-a-las-12.41.07-300x254.png', 'None');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (58, 'Martes', '22:30', '23:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (58, 'Miércoles', '01:00', '02:00', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (58, 46);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('La Contribución', 'None', 'Un espacio dedicado a el análisis de situaciones financieras');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (59, 'Lunes', '11:30', '12:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('La Hora Nacional', 'https://radio.uaa.mx/wp-content/uploads/2021/11/lahoranacional-300x300.png', 'La Hora Nacional es un programa que busca fortalecer la integración nacional a través del idioma, la cultura, las tradiciones y la creación artística.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (60, 'Domingo', '22:00', '22:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('La Terca Memoria', 'https://radio.uaa.mx/wp-content/uploads/2021/08/la-terca-memoria-300x300.png', 'Programa dedicado a la plactica de la historia de Aguascalientes.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (61, 'Viernes', '17:00', '18:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (61, 47);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (61, 48);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (61, 49);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (61, 50);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (61, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (61, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('La última y nos vamos', 'https://radio.uaa.mx/wp-content/uploads/2024/08/Captura-de-Pantalla-2024-08-08-a-las-15.32.11.png', 'Disfruta de lo mejor del regional mexicano, en compañía de Goretti Bravo');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (62, 'Jueves', '18:30', '19:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (62, 'Viernes', '00:00', '01:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (62, 'Domingo', '13:00', '14:00', 1);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Lado B', 'None', 'Presentacion de novedades musicales internacionales.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (63, 'Lunes', '02:00', '03:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (63, 'Sábado', '20:00', '21:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (63, 'Domingo', '20:00', '21:00', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (63, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Leyendas de la Música', 'https://radio.uaa.mx/wp-content/uploads/2023/06/LEYENDAS-DE-LA-MUSICA-logo-300x300.png', 'Programa musical que busca destacar la trayectoria de músicos y cantantes que se convirtieron en referentes de la cultura, brindando un aporte importante a la sociedad con su legado musical.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (64, 'Viernes', '22:00', '23:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (64, 'Domingo', '17:00', '18:00', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (64, 51);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (64, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Los hijos del maiz', 'https://radio.uaa.mx/wp-content/uploads/2024/08/428707127_956916719774290_4003942316096281218_n-298x300.jpg', 'Ari y Dany nos presentan lo mejor de la musica Rock, de la mano de entrevistas con los mejores exponentes del género acompañados de muchas sorpresas y eventos.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (65, 'Jueves', '02:00', '03:00', 1);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Radio Luxiérnaga', 'https://radio.uaa.mx/wp-content/uploads/2021/08/lux-300x300.png', 'Programa donde se analiza, de manera crítica y sencilla temas filosóficos de todas las áreas de la filosofía, es un programa de estudiantes de filosofía, de difusión filosófica que apoya el propio quehacer filosófico desde el ámbito social y para la sociedad. Es un programa de difusión filosófica para el público en general');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (66, 'Jueves', '13:30', '14:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (66, 28);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (66, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (66, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Luz para la Humanidad', 'None', 'Selección de los mejores concierto de polifonía universitaria');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (67, 'Domingo', '14:00', '15:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Mesa Abierta: Diálogos por la Cultura', 'https://radio.uaa.mx/wp-content/uploads/2021/08/dialogos-por-la-cultura-300x300.png', 'Mesa de análiss de temas culturales');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (68, 'Martes', '19:00', '19:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (68, 52);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (68, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (68, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Mexiconcierto', 'None', 'Conciertos de música clasica Mexicana.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (69, 'Sábado', '05:00', '05:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (69, 'Domingo', '05:00', '05:30', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (69, 8);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (69, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Música en Todos los Sentidos', 'None', 'Programacion de musica clasica.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (70, 'Domingo', '08:00', '09:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (70, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Natty Reggae', 'https://radio.uaa.mx/wp-content/uploads/2023/06/Logo-Natty-Reggae-300x300.png', 'Programa musical con ritmos caribeños, reggue…');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (71, 'Jueves', '00:00', '01:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (71, 'Sábado', '11:00', '12:00', 0);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (71, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Noticiero Científico y Cultural Iberoamericano (NCC)', 'https://radio.uaa.mx/wp-content/uploads/2021/08/ncc-300x300.png', 'El Noticiero Científico y Cultural Iberoamericano (NCC) fue lanzado en agosto de 2017 por la Asociación de las Televisiones Educativas y Culturales Iberoamericanas (ATEI), con el principal objetivo de apoyar la divulgación de la ciencia, la tecnología y la cultura en la región. Con la colaboración de las agencias informativas AFP, Deutsche Welle, EFE, Notimex, Xinhua, Euronews NBC, así como de los medios de información de la ONU y la NASA se difunden las noticias más relevantes de todo el mundo. El NCC es distribuido en español, inglés y portugués, en más de 19 países de Iberoamérica, además de Estados Unidos y Canadá a través de sistemas de radiodifusión, canales de TV abierta, Transmisión Directa Satelital y plataformas WebTV.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (72, 'Viernes', '10:00', '10:30', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (72, 'Sábado', '10:00', '10:30', 0);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (72, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Notas al Margen', 'https://radio.uaa.mx/wp-content/uploads/2021/08/notas-al-margen-300x300.png', 'Programa que aborda temas de filosofía desde una perspectiva diferente.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (73, 'Martes', '11:30', '12:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (73, 'Viernes', '03:30', '04:00', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (73, 53);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (73, 54);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (73, 2);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Novelas Universales', 'https://radio.uaa.mx/wp-content/uploads/2021/08/Novelas-Universales-01-300x300.png', 'Radio Teatro, que dramatiza novelas literarias de diversos autores, como Juan Rulfo, Miguel de Cervantes Saavedra, Charles Dickens, Víctor Hugo, Alejandro Dumas, etc. Con Obras Literarias como Don Quijote de la Mancha, Los Tres Mosqueteros, Oliver Twist, etc. Presentados acertadamente por Mario Vargas Llosa, escritor peruano (n. 1936), ganador del Premio Nobel de Literatura (2010), con novelas como La Tía Julia y el Escribidor, Los Cachorros, La Fiesta del Chivo, La Casa Verde, etc.');
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (74, 55);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (74, 3);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Nuevas Miradas', 'https://radio.uaa.mx/wp-content/uploads/2023/06/Nuevas-Miradas-logo-300x300.png', 'Producción radiofónica que pretende abrir espacios y visibilizar realidades distintas, desde una perspectiva informada y objetiva, de manera que se promueva la inclusión y una visión global e integrada de la sociedad.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (75, 'Jueves', '11:30', '12:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (75, 51);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (75, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Oh Là Là!', 'https://radio.uaa.mx/wp-content/uploads/2021/08/oh-la-la-300x300.png', 'Cada semana, Humberto Capetillo te lleva en un paseo por lo mejor del mundo de la música en francés, disfrutando de los diferentes géneros, ritmos, países y épocas lo componen.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (76, 'Lunes', '01:00', '02:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (76, 'Sábado', '18:00', '19:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (76, 10);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (76, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Panorama Universitario', 'None', 'Se pretende difunidir el que hacer de radio difusoras universitarias de todo el país.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (77, 'Sábado', '13:00', '14:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Piña con Canela', 'https://radio.uaa.mx/wp-content/uploads/2024/04/Captura-de-Pantalla-2024-04-10-a-las-13.12.37-300x243.png', 'Es un programa musical que invita a los radioescuchas a viajar por el mundo presentando la música más popular y contemporánea del país de elección, sumergiéndonos en diversos géneros musicales que reflejan diversidad cultural de cada lugar. Lo distintivo de «Piña con Canela» radica en que cada episodio se enfoca en un país específico, destacando las tendencias musicales emergentes.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (78, 'Sábado', '12:30', '13:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Podium Neerlandés', 'https://radio.uaa.mx/wp-content/uploads/2021/11/podiumneerlandes-300x300.png', 'Presentaciones de musica clasica desde Radio Neederlands.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (79, 'Sábado', '06:00', '07:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (79, 'Domingo', '23:00', '00:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (79, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Pollitos FM', 'https://radio.uaa.mx/wp-content/uploads/2023/08/POLLITOS-300x300.png', 'None');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (80, 'Sábado', '09:00', '10:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (80, 'Domingo', '09:00', '10:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (80, 56);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Pre-texto', 'https://radio.uaa.mx/wp-content/uploads/2021/07/pre-texto-300x300.png', 'Pre-texto difunde las actividades del Departamento Editorial y la promoción de los productos y servicios que ofrece la librería universitaria, en la sociedad y comunidad estudiantil, administrativa y profesores.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (81, 'Lunes', '14:00', '14:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (81, 57);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (81, 51);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (81, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (81, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Proiectus', 'https://radio.uaa.mx/wp-content/uploads/2023/06/Captura-de-Pantalla-2024-04-10-a-las-13.51.22-300x222.png', 'Un programa dedicado a las labores del departamento de Ciencias del Diseño y la Contrucción');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (82, 'Miércoles', '11:00', '11:30', 0);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (82, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Prospectiva 94.5', 'https://radio.uaa.mx/wp-content/uploads/2023/06/Prospectiva-94punto5-logo-300x55.png', 'Programa de análisis sobre temas de actualidad, política y sociedad.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (83, 'Lunes', '09:00', '10:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (83, 'Martes', '09:00', '10:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (83, 'Miércoles', '09:00', '10:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (83, 'Jueves', '09:00', '10:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (83, 'Viernes', '09:00', '10:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (83, 45);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (83, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (83, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (83, 7);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Pulso Noticias Edición Nocturna', 'https://radio.uaa.mx/wp-content/uploads/2023/06/Captura-de-Pantalla-2024-04-10-a-las-13.55.31.png', 'Noticiario de Radio Educación');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (84, 'Lunes', '20:00', '20:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (84, 'Martes', '20:00', '20:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (84, 'Miércoles', '20:00', '20:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (84, 'Jueves', '20:00', '20:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (84, 'Viernes', '20:00', '20:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Bloque Musical – UK Music', 'https://radio.uaa.mx/wp-content/uploads/2023/06/Captura-de-Pantalla-2024-04-10-a-las-13.56.29.png', 'Playing the best music around the world, from the UK');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (85, 'Lunes', '06:30', '07:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (85, 'Martes', '06:30', '07:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (85, 'Miércoles', '06:30', '07:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (85, 'Jueves', '06:30', '07:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (85, 'Viernes', '06:30', '07:00', 0);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (85, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Reductor Sónico', 'None', 'Prorgrama musical dedicado al Rock y sus diferentes variantes.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (86, 'Miércoles', '22:30', '23:30', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (86, 'Sábado', '21:00', '22:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Rehilete', 'https://radio.uaa.mx/wp-content/uploads/2021/11/Rehilete-boceto-logo-final1-300x300.png', 'Es un programa dedicado a niños donde se aborda cuentos, relatos, leyendas y se da información de interes enfocada en niños.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (87, 'Sábado', '08:00', '09:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Rock City', 'https://radio.uaa.mx/wp-content/uploads/2021/08/rockcity-300x300.png', 'Rock City – Donde la música no tiene límites');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (88, 'Viernes', '20:30', '22:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (88, 'Sábado', '03:30', '05:00', 1);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (88, 1);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (88, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (88, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Rutas del Agua', 'None', 'Un programa de reflexion de temas ecologicos de nuestro estado.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (89, 'Sábado', '14:00', '14:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Saber Más', 'None', 'Una ventana a la ciencia, la cultura, la geografía, la psicología, la historia, temas de tendencia, explicados en poco tiempo y de una manera amena.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (90, 'Miércoles', '13:00', '13:30', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (90, 19);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Select – BC', 'https://radio.uaa.mx/wp-content/uploads/2022/04/logo-sm-b.png', 'Programa musical de British Counsil.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (91, 'Domingo', '21:00', '22:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (91, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Sencillito', 'https://radio.uaa.mx/wp-content/uploads/2023/08/6-300x300.png', 'Un espacio dedicado a explorar nueva musica de artistas latinoamericanos.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (92, 'Viernes', '13:30', '14:00', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (92, 36);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (92, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Ser conciencia', 'https://radio.uaa.mx/wp-content/uploads/2023/06/SerCon-logo-1-01-300x300.png', 'Es un programa dedicado a la población en general, para conocer las diferentes Asociaciones y Fundaciones, sin fines de lucro, que existen en Aguascalientes, con el objetivo de identificar actividades, ubicaciones, servicios y ayuda que ofrecen, tanto a sus pacientes como a sus familiares. Además, se pretende generar mayor inclusión al abordar temáticas relacionadas a las condiciones, discapacidades, enfermedades y otras situaciones en particular que padecen algunas personas. Escuchar testimonios de pacientes o familiares que reciban apoyo.');
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (93, 19);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (93, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Sin fronteras Iberoamérica', 'None', 'Un espacio musical dedicado a la musica del flolklor latinoamericano.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (94, 'Sábado', '07:00', '08:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (94, 'Domingo', '11:00', '12:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (94, 47);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Soul, Blues, Jazz… Ayer y hoy', 'https://radio.uaa.mx/wp-content/uploads/2021/11/thumbnail_2-Soul-blues-jazz...-ayer-y-hoy-01-300x300.png', 'Es un programa musical donde se abordan diferentes evoluciones de la música.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (95, 'Lunes', '06:00', '06:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (95, 'Martes', '06:00', '06:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (95, 'Miércoles', '06:00', '06:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (95, 'Jueves', '06:00', '06:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (95, 'Viernes', '06:00', '06:30', 0);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (95, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (95, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (95, 7);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('#SoyComunicación Radio: Un nudo en la garganta', 'https://radio.uaa.mx/wp-content/uploads/2021/08/soy-comunicacion-300x300.png', 'Un espacio dedicado a mostrar el aprendizaje de los alumnos de comunicación, y de carreras externas que también llegan a tener algún proyecto de una clase por el departamento de comunicación');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (96, 'Lunes', '16:00', '17:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (96, 'Martes', '04:00', '05:00', 1);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (96, 58);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (96, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('#SoyComunicación Radio: Es Arte', 'https://radio.uaa.mx/wp-content/uploads/2024/04/Captura-de-Pantalla-2024-06-18-a-las-16.19.42-300x124.png', 'Acompaña a nuestros estudiantes del 4o. Semestre de la Licenciatura en Comunicación e Información a descubrir si sus películas, videojuegos, libros y canciones favoritas son arte… o no');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (97, 'Martes', '16:00', '17:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (97, 'Miércoles', '04:00', '05:00', 1);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('#SoyComunicación Radio: Fanáticos del fandom', 'https://radio.uaa.mx/wp-content/uploads/2024/04/277174872_1152867362205010_1555495053818311406_n-300x300.jpeg', 'Todos somos fanáticos de algo, nosotros del fandom 😄
Espacio radiofónico que da voz a los fanáticos sobre eso que les apasiona.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (98, 'Jueves', '16:00', '17:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (98, 'Viernes', '04:00', '05:00', 1);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('#SoyComunicación Radio: HollyWow', 'https://radio.uaa.mx/wp-content/uploads/2024/04/278078471_119057040737799_4942402925644699556_n-300x300.jpeg', 'Hollywow te trae todos los viernes, una nueva edición con noticias, entrevistas, cápsulas y recomendaciones sobre las series y películas que no te puedes perder.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (99, 'Lunes', '04:00', '05:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (99, 'Viernes', '16:00', '17:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Supersónico 2.0', 'https://radio.uaa.mx/wp-content/uploads/2021/11/supersonico-300x300.png', 'Programa musical que pretende compartir diferentes versiones en distintos generos de las canciones que ya conoces.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (100, 'Jueves', '01:00', '02:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (100, 'Viernes', '18:30', '19:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (100, 'Domingo', '19:00', '20:00', 1);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Tormento Tropical', 'https://radio.uaa.mx/wp-content/uploads/2023/06/Captura-de-Pantalla-2024-04-10-a-las-13.48.26-300x261.png', 'Lo-fi mx,  cumbia futurista y rebajada para viaje en el bus mientras el atardecer te daña la vista cristalizando tus las lágrimas.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (101, 'Jueves', '22:30', '23:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (101, 'Viernes', '01:00', '02:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (101, 'Sábado', '15:00', '16:00', 1);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Travesías Emprendedoras', 'None', 'Programa de Divulgación de los diferentes programas de emprendimiento de la UAA, así como casos de éxito y tips para futuros emprendedores');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (102, 'Martes', '13:00', '13:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Tu espacio', 'https://radio.uaa.mx/wp-content/uploads/2023/06/Tu-espacio-logo-300x300.png', 'Un espacio designado a la audiencia en el que se estaran mencionando datos curiosos, universitarios, y con musica a la eleccion de los radioescuchas');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (103, 'Lunes', '12:00', '13:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (103, 'Martes', '12:00', '13:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (103, 'Miércoles', '12:00', '13:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (103, 'Jueves', '12:00', '13:00', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (103, 'Viernes', '12:00', '13:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (103, 22);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (103, 8);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('UAA Noticias', 'https://radio.uaa.mx/wp-content/uploads/2021/07/uaanoticias-300x300.png', 'None');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (104, 'Lunes', '08:00', '08:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (104, 'Martes', '08:00', '08:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (104, 'Miércoles', '08:00', '08:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (104, 'Jueves', '08:00', '08:30', 0);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (104, 'Viernes', '08:00', '08:30', 0);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (104, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (104, 4);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Urbe Sessions', 'https://radio.uaa.mx/wp-content/uploads/2024/04/Captura-de-Pantalla-2024-04-10-a-las-13.04.29.png', 'Programa de Música Electrónica Global. Se incluye música de todo el mundo, nacional y local. Desde los años 70 ́s se hace música electrónica de calidad y en 1990 se posiciona a nivel comercial en el mundo. Teniendo en la actualidad una variable muy considerable de artistas, géneros y subgéneros que abonan a la riqueza de la música contemporánea actual.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (105, 'Lunes', '03:00', '04:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (105, 'Sábado', '19:00', '20:00', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Ventana al Sonido', 'https://radio.uaa.mx/wp-content/uploads/2021/08/ventana-300x300.jpg', 'Es un programa producido por el cuerpo académico UAA-CA-117, Educación y conocimiento de la música, de la Universidad Autónoma de Aguascalientes mediante la estrategia de aprendizaje situado.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (106, 'Domingo', '12:00', '13:00', 0);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (106, 59);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (106, 60);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (106, 61);
INSERT INTO programa_presentador (id_programa, id_presentador) VALUES (106, 62);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (106, 2);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (106, 4);
INSERT INTO programa_genero (id_programa, id_genero) VALUES (106, 5);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('VintagX', 'None', 'María Hernández nos trae lo más relevante y significativo sobre la Generación X: Noticias, Música, Cine, Cultura, Etc.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (107, 'Martes', '03:30', '04:00', 1);
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (107, 'Viernes', '14:00', '14:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Zona Gallos', 'https://radio.uaa.mx/wp-content/uploads/2024/04/Captura-de-Pantalla-2024-04-10-a-las-13.22.17-300x266.png', 'Programa dedicado a difundir y promover las actividades desarrolladas por el Departamento de Deportes de la Universidad Autónoma de Aguascalientes.');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (108, 'Sábado', '12:00', '12:30', 0);
INSERT INTO programa (nombre_programa, url_img, descripcion) VALUES ('Zoom Educativo', 'https://radio.uaa.mx/wp-content/uploads/2021/11/zoom-300x300.png', 'Un espacio donde se abordan temas educativos y pedagógicos');
INSERT INTO horario (id_programa, dia_semana, hora_inicio, hora_fin, es_retransmision) VALUES (109, 'Lunes', '17:30', '18:00', 0);
